version: '3.8'

services:
  ui:
    image: thesecondbread/tasty-gold-ui:0.0.2
    container_name: tasty-gold-ui
    ports:
      - "8080:80"  # Exposing UI on port 80
    depends_on:
      - backend  # Ensure backend starts first
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8081  # The UI will use this to connect to the backend

  backend:
    image: thesecondbread/tasty-gold-backend:0.0.2
    container_name: tasty-gold-backend
    ports:
      - "8081:8080"  # Exposing backend on port 8080
    environment:
      - PORT=8080
      - POSTGRES_HOST=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB_NAME=
      - POSTGRES_PORT=
      - ACCOUNT=
      - ACCESS_KEY=
      - SECRET_KEY=
      - BUCKET_NAME=